---
- name: Jenkins installation through Ansible
  hosts: jenkinsagent
  tasks:
    - name: Install Java
      yum:
        name: java-1.8.0-openjdk
        state: present

    - name: Install Wget
      yum:
        name: wget
        state: present

    - name: Install Git 
      yum:
       name: git
       state: present

    - name: Download jenkins repo
      command: wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
   
    - name: Import Jenkins CI key
      rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
        state: present
   
    - name: Install Jenkins
      yum:
        name: "jenkins"
        state: present

    - name: Enable Firewall port 
      firewalld:
         port: 8080/tcp
         permanent: yes
         state: enabled

    - name: Start Jenkins service 
      service:
        name: jenkins
        state: started
    
    
    

       
       
        

